language: csharp
mono: none
dotnet: 2.1
before_install:
  # restore dependencies from the private feed
  - dotnet nuget locals --clear all
  - dotnet restore -s https://www.myget.org/F/paranamix2/ 
script:
  - dotnet build 